name: test_actions

on:
  push:

jobs:
  test_actions:

    # define the operating systems and R versions we want to test on
    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: ubuntu-latest}
        - { os: ubuntu-24.04-arm}

    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    # steps to run in the defined environments
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
    
      - name: setup tinytex
        uses: r-lib/actions/setup-tinytex@v2
        env:
          TINYTEX_VERSION: 2025.01
          TINYTEX_INSTALLER: TinyTeX
